server:
  # debug release test
  model: release
  port: 8888
  cors: true
  tls:
    enable: false
    key-file: ./default.key
    cert-file: ./default.pem
  # 机器终端操作回放文件存储路径
  machine-rec-path: ./rec
jwt:
  # jwt key，不设置默认使用随机字符串
  key: #JWT_KEY#
  # 过期时间单位分钟
  expire-time: 1440
# 资源密码aes加密key
aes:
  key: #AES_KEY#
mysql:
  host: #MYSQL_HOST#
  username: #MYSQL_USER#
  password: #MYSQL_PASSWORD#
  db-name: #MYSQL_DB#
  config: charset=utf8&loc=Local&parseTime=true
  max-idle-conns: 5
log:
   # 日志等级, trace, debug, info, warn, error, fatal
  level: info
  # file:
  #   path: ./
  #   name: mayfly.log